### ISSUE TITLE
数据不刷新

### ISSUE THREAD

**Issue by wzgiceman** [xiepeijie/SwipeCardView#14]
控制的第一页在数据被更改以后，adapter调用notifyDataSetChanged执行了getView方法，但没有正确显示出来；同样的问题，动态反复设置数据，第一页也是显示有问题，但是轮循一圈以后正常！

**Comment by xiepeijie** [comment]
@wzgiceman 额，我看看

**Comment by jiancao** [comment]
请问这个问题解决了吗？
