### ISSUE TITLE
一个bug

### ISSUE THREAD

**Issue by yaojunyi3721** [xiepeijie/SwipeCardView#36]
itemView里有seekbar和Textview,textview用于展示当前seekbar的分数 当seekbar滑动时更新textview的文本,当seekbar的值从9到10时会导致textview显示为1,即textview内容显示不全
其他地方不变 改为listview就无此问题

**Comment by yaojunyi3721** [comment]
xml布局文件中textview的默认值为单数,seekbar max=10  当seekbar从9滑动到10时 会导致textview显示为1
当设置max=100时 在seekbar只会显示出最高位,比如progress是25时显示为2,progress是100时显示为1

**Comment by xiepeijie** [comment]
@yaojunyi3721 你可以先在itemView上加上android:clipChildren="false"属性 试试
