### ISSUE TITLE
Show like/dislike image on card when touched.

### ISSUE THREAD

**Issue by rajeevjaiswal** [xiepeijie/SwipeCardView#4]
@xiepeijie Is is possible to show like/dislike image the moment I touch the card? Both the images should be visible initially and depending on the swipe (left/right) one should get invisible. If user is moving the card left then dislike image should remain visible and the like image should disappear

**Comment by xiepeijie** [comment]
@rajeevjaiswal It is possible. you can use the method.
```
@Override
public void onScroll(float progress, float scrollXProgress) {
    likeView.setAlpha(scrollXProgress);
    dislikeView.setAlpha(1-scrollXProgress);
}
```
