### ISSUE TITLE
simpledraweeview  的用处是什么？

### ISSUE THREAD

**Issue by hujingting** [xiepeijie/SwipeCardView#8]
你好，我用的过程中一定几率会出现InvocationTargetException on inflating an xml - 异常， studio提示是simpledraweeview 中有问题。

**Comment by xiepeijie** [comment]
@hujingting fresco不知道吗

**Comment by hujingting** [comment]
@xiepeijie 知道了，我现在用的是picasso加载图片，是因为这个原因吗？

**Comment by xiepeijie** [comment]
@hujingting 恩恩，你可以用自己的图片加载框架

**Comment by hujingting** [comment]
好的，谢谢，不过我把xml里面的com.....simpledraweeview直接换成imageView好像又能正常显示了，不知道以后会不会有坑

**Comment by xiepeijie** [comment]
@hujingting 你只是换了图片加载，有坑也与这个替换无关
